use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    // Keywords
    Match,
    Optional,
    Where,
    Return,
    With,
    Unwind,
    Union,
    Order,
    By,
    Asc,
    Ascending,
    Desc,
    Descending,
    Skip,
    Limit,
    Create,
    Delete,
    Detach,
    Set,
    Remove,
    Merge,
    On,
    And,
    Or,
    Xor,
    Not,
    In,
    Is,
    Null,
    True,
    False,
    As,
    Distinct,
    All,
    Case,
    When,
    Then,
    Else,
    End,
    Starts,
    Ends,
    Contains,
    Exists,
    Count,

    // Identifiers and literals
    Ident(String),
    Integer(i64),
    Float(f64),
    StringLit(String),

    // Parameter
    Parameter(String),

    // Punctuation
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Dot,
    DotDot,
    Comma,
    Colon,
    Semicolon,
    Pipe,

    // Operators
    Eq,
    Neq,
    Lt,
    Gt,
    Lte,
    Gte,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    PlusEq,
    RegexEq,

    // End of input
    Eof,
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Token::Match => write!(f, "MATCH"),
            Token::Optional => write!(f, "OPTIONAL"),
            Token::Where => write!(f, "WHERE"),
            Token::Return => write!(f, "RETURN"),
            Token::With => write!(f, "WITH"),
            Token::Unwind => write!(f, "UNWIND"),
            Token::Union => write!(f, "UNION"),
            Token::Order => write!(f, "ORDER"),
            Token::By => write!(f, "BY"),
            Token::Asc => write!(f, "ASC"),
            Token::Ascending => write!(f, "ASCENDING"),
            Token::Desc => write!(f, "DESC"),
            Token::Descending => write!(f, "DESCENDING"),
            Token::Skip => write!(f, "SKIP"),
            Token::Limit => write!(f, "LIMIT"),
            Token::Create => write!(f, "CREATE"),
            Token::Delete => write!(f, "DELETE"),
            Token::Detach => write!(f, "DETACH"),
            Token::Set => write!(f, "SET"),
            Token::Remove => write!(f, "REMOVE"),
            Token::Merge => write!(f, "MERGE"),
            Token::On => write!(f, "ON"),
            Token::And => write!(f, "AND"),
            Token::Or => write!(f, "OR"),
            Token::Xor => write!(f, "XOR"),
            Token::Not => write!(f, "NOT"),
            Token::In => write!(f, "IN"),
            Token::Is => write!(f, "IS"),
            Token::Null => write!(f, "NULL"),
            Token::True => write!(f, "TRUE"),
            Token::False => write!(f, "FALSE"),
            Token::As => write!(f, "AS"),
            Token::Distinct => write!(f, "DISTINCT"),
            Token::All => write!(f, "ALL"),
            Token::Case => write!(f, "CASE"),
            Token::When => write!(f, "WHEN"),
            Token::Then => write!(f, "THEN"),
            Token::Else => write!(f, "ELSE"),
            Token::End => write!(f, "END"),
            Token::Starts => write!(f, "STARTS"),
            Token::Ends => write!(f, "ENDS"),
            Token::Contains => write!(f, "CONTAINS"),
            Token::Exists => write!(f, "EXISTS"),
            Token::Count => write!(f, "COUNT"),
            Token::Ident(s) => write!(f, "{s}"),
            Token::Integer(n) => write!(f, "{n}"),
            Token::Float(n) => write!(f, "{n}"),
            Token::StringLit(s) => write!(f, "'{s}'"),
            Token::Parameter(s) => write!(f, "${s}"),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::LBracket => write!(f, "["),
            Token::RBracket => write!(f, "]"),
            Token::LBrace => write!(f, "{{"),
            Token::RBrace => write!(f, "}}"),
            Token::Dot => write!(f, "."),
            Token::DotDot => write!(f, ".."),
            Token::Comma => write!(f, ","),
            Token::Colon => write!(f, ":"),
            Token::Semicolon => write!(f, ";"),
            Token::Pipe => write!(f, "|"),
            Token::Eq => write!(f, "="),
            Token::Neq => write!(f, "<>"),
            Token::Lt => write!(f, "<"),
            Token::Gt => write!(f, ">"),
            Token::Lte => write!(f, "<="),
            Token::Gte => write!(f, ">="),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Star => write!(f, "*"),
            Token::Slash => write!(f, "/"),
            Token::Percent => write!(f, "%"),
            Token::Caret => write!(f, "^"),
            Token::PlusEq => write!(f, "+="),
            Token::RegexEq => write!(f, "=~"),
            Token::Eof => write!(f, "EOF"),
        }
    }
}
